Question 1:

Answer:

In [1]:
import numpy as np
npArr=np.arange(2,50,3)
print(npArr)`

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Question 2:

Answer:

In [5]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

10
2
3
1
4
5
8
9
7
6
[ 1  2  3  4  5  6  7  8  9 10]


Question 3:

Answer:

In [6]:
npArr=np.array([1,2,3,4,5,6])
print(npArr.ndim)
print(npArr.size)

1
6


Question 4:

Answer:Here we have made use np.newaxis.


In [11]:
npArr = np.array([1,2,3,4,5,6,7])
print(npArr)
print(npArr.shape)
npArr1=npArr[:, np.newaxis]
print(npArr1)
print(npArr1.shape)
npArr2 = npArr[np.newaxis,:]
print(npArr2)
print(npArr2.shape)

[1 2 3 4 5 6 7]
(7,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(7, 1)
[[1 2 3 4 5 6 7]]
(1, 7)


Here I have made use of np.expand_dims

In [17]:
import numpy as np
x = np.zeros((3, 4))
print(x)
print(x.shape)
y = np.expand_dims(x, axis=1) 
print(y) 
print(y.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]
(3, 1, 4)


Question 5:

Answer:

In [25]:
f = np.array([[1,2,3],[4,5,6]])
g = np.array([[7,8,9],[10,11,12]])

print("Horziontal stack")
print(np.hstack((f, g)))
print("Vertical stack")
print(np.vstack((f, g)))

Horziontal stack
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical stack
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Question 6:

Answer:Python's numpy library has np.unique funciton which returns the sorted unique elements and their frequency. Below I have made use of this.

In [31]:
npArr = np.array([1,1,1,1,3,3,2,2,4,5,67,89,800,0,200,200,4,81,7])
u,c =np.unique(npArr,return_counts=True)
print('unique elements are: ',u)
print('Their frequcency is:',c) 

unique elements are:  [  0   1   2   3   4   5   7  67  81  89 200 800]
Their frequcency is: [1 4 2 2 2 1 1 1 1 1 2 1]
